In [78]:
name = "Hey there this is XYZ"
name.split()

['Hey', 'there', 'this', 'is', 'XYZ']

In [79]:
planet = "Earth"
diameter = 12472
print(f"The diameter of {planet} is {diameter} kilometer")

The diameter of Earth is 12472 kilometer


In [80]:
nest_dict = {"k1":[1,2,3,
                   {"tricky":["oh","man","inception",
                              {"target":[1,2,3,"hello"]
                              }]}]
            }

print(nest_dict["k1"][3]["tricky"][3]["target"][3])

hello


In [81]:
# Import Library
import numpy as np

In [82]:
# Array of 10 zeros 
np_10 = np.zeros(10)
np_10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
np_evn = np.arange(20,36,2) # start , stop , steps 
np_evn

array([20, 22, 24, 26, 28, 30, 32, 34])

In [84]:
np_3 = np.arange(0,9).reshape(3,3) # generate number and convert to 3x3 matrix
np_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
num_1 = np.array([1,2,3]) # create array 1
num_2 = np.array([4,5,6]) # create array 2
concat = np.concatenate((num_1,num_2),axis=None)
concat

array([1, 2, 3, 4, 5, 6])

In [86]:
# Import Library
import pandas as pd 

In [87]:
# create random elements
ran_num = np.random.randint(10,size=(3,2))
df = pd.DataFrame(ran_num,columns=["row1","row2"])
df

row1  row2
0     6     6
1     0     7
2     8     9

In [88]:
# another convinient method
pd_dict = {
    "col_a":[1,2,3],
    "col_b":[2,5,6]
          }
# Create dataframe
df = pd.DataFrame(pd_dict)
df

col_a  col_b
0      1      2
1      2      5
2      3      6

In [89]:
name_list = ["ZYNAB",20],["BHAVANA",20],["VAISHALI",20],["KANCHANA",19]
df = pd.DataFrame(name_list,columns=["Name","Age"])
df

Name  Age
0     ZYNAB   20
1   BHAVANA   20
2  VAISHALI   20
3  KANCHANA   19

In [90]:
import pandas as pd
# calling dataframe constructor 
df = pd.DataFrame()
# create date 
df["time"] = pd.date_range(start="1/1/2023",end="2/10/2023",freq="24H")

# Extract features
df["year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["day"] = df["time"].dt.day

In [91]:
df.head()


time  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-02  2023      1    2
2 2023-01-03  2023      1    3
3 2023-01-04  2023      1    4
4 2023-01-05  2023      1    5

In [92]:
lists = [[1,"aaa",22],[2,"bbb",25],[3,"ccc",24]]
df = pd.DataFrame(lists,columns=["col1","col2","col3"])
df

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24